### ISSUE TITLE
dwi-shard.md: add link to code for release 3

### ISSUE THREAD

**Issue by maxpietsch** [BioMedIA/dHCP-release-notes#14]

**Comment by dchristiaens** [comment]
Link to the new repository: https://github.com/dchristiaens/dhcp-shard-pipeline

**Comment by dchristiaens** [comment]
I have added the link to the docs in https://github.com/BioMedIA/dHCP-release-notes/commit/541de74ea9bf9b53520d05e2b66378c43f58a3e2
