### ISSUE TITLE
region labels for Draw-EM tissue segmentation (9 labels)	

### ISSUE THREAD

**Issue by nogakertes** [BioMedIA/dHCP-release-notes#27]
Hi,
Where can I find the labels for Draw-EM tissue segmentation (9 labels)? 
Thanks!
Noga

**Comment by v-kyriakopoulou** [comment]
[fetal DrawEM  v1.2 label IDs.xlsx](https://github.com/BioMedIA/dHCP-release-notes/files/14884750/fetal.DrawEM.v1.2.label.IDs.xlsx)

**Comment by nogakertes** [comment]
Thank you!
